FROM advrisc/u14.04-410clbv1

# openwrt
RUN apt-get update
RUN apt-get install -y gcc g++ binutils patch autoconf libcurl4-openssl-dev bzip2 flex make gettext pkg-config unzip zlib1g-dev libc6-dev subversion git libncurses5-dev gawk sharutils curl libxml-parser-perl python-yaml ocaml-nox ocaml ocaml-findlib libssl-dev

RUN apt-get install -y bsdmainutils

